[package]
name = "frenzy"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
memmap2 = "0.9"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
# strip = true
panic = 'abort'

[profile.profiling]
inherits = "release"
debug = true
